"""adding index to Customer

Revision ID: b4f0461573c0
Revises: 0743b1523d4e
Create Date: 2025-01-08 00:41:45.651488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4f0461573c0"
down_revision: Union[str, None] = "0743b1523d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_hash_customer_fullname",
        "customer",
        ["customer_fullname"],
        unique=False,
        postgresql_using="hash",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_hash_customer_fullname",
        table_name="customer",
        postgresql_using="hash",
    )
    # ### end Alembic commands ###
