"""Sync database changes

Revision ID: 5dc160685a3e
Revises: b4f0461573c0
Create Date: 2025-01-09 11:11:25.640575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5dc160685a3e"
down_revision: Union[str, None] = "b4f0461573c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "json_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        """
        CREATE INDEX json_orders_data_gin_trgm_idx
        ON json_orders
        USING gin ((data::TEXT) gin_trgm_ops);  -- добавлены скобки!
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "json_orders_data_gin_trgm_idx",
        table_name="json_orders",
        postgresql_using="gin",
        postgresql_ops={"data": "gin_trgm_ops"},
    )
    op.drop_table("json_orders")
    # ### end Alembic commands ###
